sudo: required
services:
    - docker
    
before_install:
    - docker build -t akhilbansalgmail/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run akhilbansalgmail/react-test npm run test -- --coverage

after_success:
    - docker build -t akhilbansalgmail/multi-client ./client
    - docker build -t akhilbansalgmail/multi-nginx ./nginx
    - docker build -t akhilbansalgmail/multi-server ./server
    - docker build -t akhilbansalgmail/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push akhilbansalgmail/multi-client
    - docker push akhilbansalgmail/multi-nginx
    - docker push akhilbansalgmail/multi-server
    - docker push akhilbansalgmail/multi-worker